### ISSUE TITLE
[QPROF] QueryProfilerInterface MVP Specification

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#1059]
### Goal
Build a Minimum Viable Product (MVP) for the `QueryProfilerInterface` with essential features.

### Tasks

1. **Inheritance from QueryProfiler** [Essential] - @roypaulin 
   - [x] Ensure that `QueryProfilerInterface` inherits from the `QueryProfiler` base class.

2. **Jupyter Widgets Integration** [Essential] - @roypaulin 
   - [x] Utilize Jupyter Widgets for creating an interactive user interface.

3. **Tree Representation** [Essential] - @roypaulin 
   - [x] Implement the representation of the object using the tree generated by `get_qplan_tree` method.

4. **Buttons for Configuration** [Essential] - @roypaulin 
   - [x] Add buttons to the interface for configuring tree metrics and colors.

5. **Clickable Tree** [Essential] - @roypaulin 
   - [ ] Implement the tree to be clickable.
   - [ ] Capture the tree path_id on click and update the URL for easy navigation.

6. **Actions on Tree Click** [Essential] - @roypaulin 
   - [ ] Define and implement actions on tree click, such as displaying elements (for example: path_id information) and pruning the tree.

7. **Step Navigation** [Important] - @roypaulin 
   - [x] Create a mechanism for easy navigation between different steps in the process.

8. **Display Important Information** [Important] - @roypaulin 
   - [ ] Implement a section to prominently display important information like SQL query, execution time, and version.

9. **View Statements and Query IDs** [Optional] - @jslaunwhite-microfocus and @oualib 
   - [x] Implement a feature to view all statements and query IDs of a specified schema.
   - [x] Enable navigation through statements and query IDs.

10. **Customer Information** [Optional] - @jslaunwhite-microfocus and @oualib 
   - [ ] Develop functionality to view customer information related to a selected statement or query ID.
   - [x] Change the name of the generated tables to be able to retrieve and understand easily the query we are profiling.
   - [ ] Being able to export and import using PARQUET.
 
11. **Tree Customization** [Important] - @oualib 
   - [x] Being able to use 2 metrics.
   - [x] Adding more metrics and the way we want to aggregate (SUM, MAX...).
   - [x] Icon for each node type.

12. **Charts Improvements** [Optional] - @oualib 
  - [ ] Adding Boxplot as an option for graphics using multiple nodes for the different path IDs.
  - [ ] Being able to round numbers.

### Note
This MVP aims to establish the foundational elements of the `QueryProfilerInterface`. Focus on completing the tasks incrementally, and it is acceptable to defer non-essential features for future iterations.

### Ref
https://saturncloud.io/blog/understanding-jupyter-notebook-widgets/

**Comment by oualib** [comment]
We can close the MVP as the first version was released. If we need further improvement, we will open new issues.
