### ISSUE TITLE
[Website] VerticaPy Website - Iteration 2 - Epic

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#1090]
The documentation is almost finalised, we need small improvement to make it better:

- [x] Comparison Page: We should have a page near to Benchmark with a table and all the ABS ERROR used to compare against other library (ex. sklearn, statsmodel...) - @vikash018 and @mail4umar and @oualib 
- [x] Correct favicon for inner folder like api or notebooks
- [x] Missing Customers Use-cases. - @oualib 
- [x] Rebuilding the examples notebook with the most recent version. - @mail4umar 
- [x] VerticaPy Newsletter. - @mail4umar and @tconsigny 
- [x] GIF background should be transparent. - @mail4umar 
- [x] Plotting Page in vDataFrame: Having access to all the different classes and explaining them. - @mail4umar 
- [x] Copy paste problem for code - @mail4umar 
- [x] Increase Font Size but keeping the website consistency (maybe increase the initial percentage ratio?). - @mail4umar 
- [x] Updating the VerticaPy Cheat Sheet + adding a link to it in the README. - @mail4umar 
- [x] Next/Previous pages are using the entire reference instead of using the child reference. This can be solved by using regex on div class="title" on class "page_info". - @mail4umar 
- [x] README: Adding GIF for chart gallery and all the graphics + section on LIGHT/DARK mode. - @mail4umar 
- [x] Correlation Matrix - Transparent - @oualib 
- [x] Finalising the v1.0.1 and updating the doc what's new. - @oualib 
- [x] Update GitHub README page + remove contributing (adding it in the README and redirecting to the right page of the website). Adding a link to the old website www.vertica.com/python/old and explain that it will be soon removed. We advice to update to 1.0.0 minimum. - @oualib 
- [x] Documentation Header should work on small screen. - @oualib 
- [x] Change black color to something more adapted for SPHINX mode. - @oualib 
- [x] Make the documentation header responsive on mobiles. - @oualib  
- [x] Support Dark Mode for our pictures. - @oualib 
- [x] Graphviz: Supporting dark mode and correcting the tree export (icons are not displayed correctly and no tooltip). - @oualib

**Comment by vikash018** [comment]
Can we use BOLD text for function parameters names? Atteched example from pandas doc.
![pandas](https://github.com/vertica/VerticaPy/assets/29343439/b5def191-c982-422c-a8de-ba50d4812097)
![VerticaPy](https://github.com/vertica/VerticaPy/assets/29343439/3c39899b-465e-419b-95aa-9b4223b854da)

**Comment by oualib** [comment]
Closing this ticket, we will work on a 3rd iteration.
