### ISSUE TITLE
[Website] VerticaPy Website - Iteration 3 - Epic

### ISSUE THREAD

**Issue by oualib** [vertica/VerticaPy#1170]
### What is the requested change?

The documentation is almost finalised, we need small improvement to make it better:

- [x] Update time series page with BY parameters - @mail4umar 
- [ ] Problems with the main pages videos. - @oualib 
- [ ] Showcase Website: Pages for: Why VerticaPy? First Logo? History? Why Choose us? - @oualib 
- [ ] Generating 5 minutes Videos for each User Guide Page. - @oualib 
- [ ] Lazy Loading Mode to avoid high loading time when navigating through pages like Chart Gallery or classes. - @mail4umar 
- [ ] User Guide: Rebuilding the user guide and adapting it to our current format (RST) - Next Step would be to add videos. - @mail4umar and @tconsigny 
- [ ] Comparison Page 2: We should have a comparison page for aggregations, correlations and other statistical functions like tests or iv_woe ... - @mail4umar

**Comment by oualib** [comment]
We decided to change the plan for this ticket.

Some internal decisions are made and we've created a specific JIRA ticket: https://jira.verticacorp.com/jira/browse/VER-97270

The doc will become independent without the need of the micro-website.
